### ISSUE TITLE
Please update functions.php

### ISSUE THREAD

**Issue by fac3-SMC** [onelogin/moodle-saml#13]
Hi,

Can you please update functions.php on v2.4.2? When we worked on fixing the provisioning issue with the Moodle plugin the only version that was updated was v2.5.1. This version currently supports Moodle 3.4 and our SP has not transitioned our implementation up to that version yet. Can you please update the code in the functions.php in V2.4.2? This will help us fix this ongoing issue.

Thanks!

**Comment by pitbulk** [comment]
Do you mean release a 2.4.3 version with the following changes https://github.com/onelogin/moodle-saml/commit/14ac4a3da68d08682311670f4e7c63a8852b8e61 ?

**Comment by fac3-SMC** [comment]
Sixto,

	I will have them test and get back to you.

Regards,
- Francisco Chavez

----------------------------------------------------------------------------------- 
Francisco Chavez
Manager, IT Security | Saint Mary's College of California
925-631-8236 | fac3@stmarys-ca.edu <mailto:fac3@stmarys-ca.edu>

**Comment by pitbulk** [comment]
any news?

**Comment by fac3-SMC** [comment]
Sixto,

	Good Morning. I guess no news is good news? I really appreciate you following up with us. This definitely fixed the issue we were having. We had the module moved into production and no longer experience any issues when accounts are provisioned.

Thank you for all your help!

Regards,
- Francisco Chavez

----------------------------------------------------------------------------------- 
Francisco Chavez
Manager, IT Security | Saint Mary's College of California
925-631-8236 | fac3@stmarys-ca.edu <mailto:fac3@stmarys-ca.edu>
