### ISSUE TITLE
Role mapping does not work

### ISSUE THREAD

**Issue by semteacher** [onelogin/moodle-saml#14]
Hello. I have tried to introduce role mapping on my Moodle. with this plugin but it does not work
Basic saml auth working fine - users can to log-in. 
So, my Moodle saml plugin role mapping settings:
https://www.screencast.com/t/KGG2BYa5
And OneLogin SAML assertion example:
https://www.screencast.com/t/1oZijL3iqW6
UPD: Ihave installed latest "master" code (ahead 2.5.1)

**Comment by pitbulk** [comment]
Are you sure the IdP is providing the role attribute as "member".
Use [SAML Tracer](https://addons.mozilla.org/es/firefox/addon/saml-tracer/) in order to record the SAMLResponse sent by the IdP and verify the name of the attribute providing the role info.

**Comment by semteacher** [comment]
You right! I am sorry, missed setting's param.
However, one more issue exist. 
Does plugin currently support Moodle custom created profile fields? They are listed in plugin settings.
But when I tried to map one such field - got this error:
```
Debug info: Unknown column 'profile_field_mcohort' in 'field list'
UPDATE mdl_user SET profile_field_mcohort = ? WHERE id = ?
[array (
0 => 'Public Student',
1 => '399',
)]
Error code: dmlwriteexception
```
Standard fields has been mapped succesfully

**Comment by pitbulk** [comment]
profile_field_mcohort is not part of the mdl_user table, that why you get that SQL exception.

What you did in order to support that 'mcohort' field?

**Comment by semteacher** [comment]
> What you did in order to support that 'mcohort' field?
Actually, I have created this field as well as several other custom fields.
This field just appear in list of available fields in moodle-saml plugin settings.
Small explanation. I have tested approaches of saml login.
And I have installed another saml plugin (saml2). It is inactive right now. 
https://www.screencast.com/t/O7mNUhgkC8h0
But in his interface - also all possible fields listed...
