### ISSUE TITLE
auth failed due to missing username/email saml attribute

### ISSUE THREAD

**Issue by rikunashoujo** [onelogin/moodle-saml#19]
I keep getting this error even though IDP sends the attributes correctly. Tried to make the attribute names identical with the IDP but still can't get it to work. 
SAML Summary of IDP:

Issuer                      = www.bablah.com
Subject                     = testing@bablah.com
NameID                      = testing@bablah.com

AttributeStatement:
 * username                                                           = testing@bablah.com
 * email                                                              = testing@bablah.com
 * firstname                                                          = My Name
 * lastname                                                           = My Last

error/auth_onelogin_saml: auth failed due to missing username/email saml attribute: <br />The identity provider returned a set of data that does not contain the SAML username/email mapping field. Once of this field is required to login. <br />Please check your Username/Email Address Attribute Mapping configuration.

Any idea?

**Comment by pitbulk** [comment]
You need to place the same value that has the Name of the Attribute in the Attribute Mapping section.

**Comment by pitbulk** [comment]
I guess the issue was #17
