### ISSUE TITLE
implementing Event API ?

### ISSUE THREAD

**Issue by ak4t0sh** [onelogin/moodle-saml#20]
Event API allow a plugin to send a message to the system and allow others plugins to react to those "event"
For example when user profile is updated like in https://github.com/onelogin/moodle-saml/blob/f76e1470722e9d2fc77fe6c6d205ad3090f316e4/auth/onelogin_saml/functions.php#L213 
you should trigger `\core\event\user_updated` or better use [user_update_user](https://github.com/moodle/moodle/blob/efb3d4e7a7ba5ea0126e55981aa8c564a02b07fc/user/lib.php#L145) which will handle it for you.
For example missing `\core\event\user_updated` triggering cause an issue in [local_autogroup](https://github.com/emmarichardson/local_autogroup) which lead to inconsistency in user groups (see : https://github.com/emmarichardson/local_autogroup/issues/28)

**Comment by pitbulk** [comment]
I see, do you have a PR to add such support?

**Comment by ak4t0sh** [comment]
No and unfortunately I won't be able to work on this soon.

**Comment by pitbulk** [comment]
I believe this PR adds what you were looking for. https://github.com/onelogin/moodle-saml/pull/22

Can you verify that this fixes the issue you were experienced?
(Notice the fact of triggering the event will be controlled by a flag on the settings.

**Comment by ak4t0sh** [comment]
pinging @luiggisanso (who reported the issue on local_autogroup). Could you test this PR please ?

**Comment by luiggisanso** [comment]
I'm pinging @irolley too ;-)
We'll test it asap

**Comment by irolley** [comment]
Thanks for the fix @pitbulk, I'll test it later today.

**Comment by irolley** [comment]
**Tested and it seems good** (auto group gets notified and updates accordingly), congrats!

I didn't get the text strings though. Is there a "build" command to run ?

![image](https://user-images.githubusercontent.com/49037213/119985735-55909a00-bfc3-11eb-9278-aef8dc7c7018.png)


@pitbulk do you think this is stable enough for production use?

Thanks to you both @pitbulk and @ak4t0sh !

**Comment by irolley** [comment]
Also… I think this should be the default behaviour and it should not be turned off ; I don't see why this should be an optional setting. What do you think ?

**Comment by pitbulk** [comment]
It gonna change the current behavior, so if other customers have similar plugins, they will experience a behavior change not expected.

I prefer always to add behavior changes as something optional, managed by settings

**Comment by ak4t0sh** [comment]
Thanks for the fix @pitbulk !
Indeed adding it as an option to prevent sudden behavior changes is a good idea for now.
However as this event is the standard and expected behavior when an user is updated IMO it should be enable by default in a future release
