### ISSUE TITLE
Bug when group updated from custom field (AutoGroup & OneLogin)

### ISSUE THREAD

**Issue by luiggisanso** [onelogin/moodle-saml#24]
Hi

As I don't know if this is an AutoGroup or OneLogin problem, I will also post this message here.
The related issue from AutoGroup : https://github.com/emmarichardson/local_autogroup/issues/31

We have a bug with group changes from custom fields for accounts with OneLogin authentication.

When you manually change the group from the user's profile, you have to save it twice so that in the course the group is updated.

For accounts with authentication set to "manual", the change is immediate.

Is this a communication problem between AutoGroup and the profile of users with specific authentication or a problem with OneLogin as well?

A little video to illustrate my problem

https://youtu.be/WJ2h4XRpKTc

Hope it's understanding...

**Moodle 3.11.3+ (Build: 20211008)
local_autogroup | 2.5 | 2020072700
auth_onelogin_saml | 2021010101**

Cheers.

**Comment by pitbulk** [comment]
Have you tried to disable the local_autogroup module and see if you are able to reproduce the bug?

**Comment by luiggisanso** [comment]
Hi

Well, it's now fixed.
We have the latest version from github with the new fonction "trigger event" (committed on 26 May)

So I can close this issue ;-)

Thanks
