### ISSUE TITLE
Moodle PHP one login SAML error

### ISSUE THREAD

**Issue by sulaganathan** [onelogin/moodle-saml#3]
Hi

One of our client is requested us to review the one login SAML plugin and when we do so we got some error on QA.

After enabled the onelogin and when we do logging out, we got the following error.

Exception - Invalid array settings: idp_entityId_not_found, idp_sso_not_found

More information about this error

Debug info: 
Error code: generalexceptionmessage
Stack trace:
line 107 of /auth/onelogin_saml/lib/Saml2/Settings.php: OneLogin_Saml2_Error thrown
line 76 of /auth/onelogin_saml/lib/Saml2/Auth.php: call to OneLogin_Saml2_Settings->__construct()
line 80 of /auth/onelogin_saml/index.php: call to OneLogin_Saml2_Auth->__construct()
Output buffer: <br /> <b>Notice</b>: Undefined property: stdClass::$saml_strict_mode in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>46</b><br /> <br /> <b>Notice</b>: Undefined property: stdClass::$saml_debug_mode in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>47</b><br /> <br /> <b>Notice</b>: Undefined property: stdClass::$saml_nameid_encrypted in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>72</b><br /> <br /> <b>Notice</b>: Undefined property: stdClass::$saml_authn_request_signed in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>73</b><br /> <br /> <b>Notice</b>: Undefined property: stdClass::$saml_logout_request_signed in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>74</b><br /> <br /> <b>Notice</b>: Undefined property: stdClass::$saml_logout_response_signed in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>75</b><br /> <br /> <b>Notice</b>: Undefined property: stdClass::$saml_want_message_signed in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>76</b><br /> <br /> <b>Notice</b>: Undefined property: stdClass::$saml_want_assertion_signed in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>77</b><br /> <br /> <b>Notice</b>: Undefined property: stdClass::$saml_want_assertion_encrypted in <b>/var/www/mrhosts/V_20_NEXT_QA/auth/onelogin_saml/functions.php</b> on line <b>78</b><br />

![logout_error](https://cloud.githubusercontent.com/assets/11982111/10968716/1aba2958-83e9-11e5-8cd9-095301609f98.png)

We have tested in one login PHP SAML version 2015081001 on Moodle 2.8

Please suggest the fixes

**Comment by pitbulk** [comment]
I will deploy a fresh moodle 1.8, install  and review the plugin and fix it asap.

Thanks for report the bug.

**Comment by sulaganathan** [comment]
Hi

You mentioned Moodle version as 1.8 but the Moodle version is 2.8.

**Comment by pitbulk** [comment]
Typo ;)

**Comment by pitbulk** [comment]
@sulaganathan can you access to the SAML settings, review that all info is there, save and try again the SSO and SLO flow?

**Comment by sulaganathan** [comment]
Hi @pitbulk 

I will check and let you know

**Comment by pitbulk** [comment]
I deployed a fresh moodle 2.8 with the onelogin_saml [2.0.2](https://github.com/pitbulk/moodle-onelogin/releases/tag/v2.0.2) (same than the master branch) and had no errors.

I can't reproduce the error that you mention. 
My theory: The code of the plugin was updated, but the settings where no refreshed.
