### ISSUE TITLE
error/auth_onelogin_saml: auth failed due to missing username/email saml attribute

### ISSUE THREAD

**Issue by DaRockWildCoder** [onelogin/moodle-saml#4]
I have just plugued together my moodle to onelogin.
Once all steps in this guide is done : 
https://onelogin.zendesk.com/hc/en-us/articles/201173644-Configuring-SAML-for-Moodle2

I get this error : 

error/auth_onelogin_saml: auth failed due to missing username/email saml attribute: 
The identity provider returned a set of data that does not contain the SAML username/email mapping field. Once of this field is required to login. 
Please check your Username/Email Address Attribute Mapping configuration.

Now, I can't login with admin user to my Moodle.

What are the steps to solve this.

Thanks

P-L

**Comment by pitbulk** [comment]
You can access to <moodle-base-url->//login/index.php?normal  in order to be able to log as an admin.

You need to set up the Attribute Mapping values, as suggested in the message:
"Please check your Username/Email Address Attribute Mapping configuration."

Moodle need to know the names of the attributes sent by OneLogin.

**Comment by DaRockWildCoder** [comment]
Hi @pitbulk ,

I see that if you forget to change the value in the database, you'll get this kind of error and should not be able to log back.

You should add a new step after step 10.
Here's the query to run for **step 11** : 

**MySql Query**

```
UPDATE moodle162.mdl_config set value=1 
WHERE name='alternateloginurl';
```

After I log back to Moodle with admin account, I configure the section

**ATTRIBUTE MAPPING**
*type the followin in the appropriate textbox :*
```
Username : username
Email Address : email	
```

Disconnect from your admin account.
Reconnect using the login button on top right.
You should be redirect to onelogin login page.
Use your credential for onelogin account.

Once you're connected, you're redirected to your moodle with this error : 

```
error/auth_onelogin_saml: auth failed due to missing username/email saml attribute: 
The identity provider returned a set of data that does not contain the SAML username/email mapping field. Once of this field is required to login. 
Please check your Username/Email Address Attribute Mapping configuration.
```

What are the config to change to make this work properly ?

Regards,

DaRockWildCoder

**Comment by pitbulk** [comment]
Are you sure the IdP is sending username and email attributes? Can you share the SAMLResponse (record it with SAML Tracer).

**Comment by DaRockWildCoder** [comment]
Hi @pitbulk ,

I see that OneLogin is sending this SAML parameter to Moodle : 

```
<saml:AttributeStatement>
         <saml:Attribute Name="saml_username" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
            <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">***@****.com</saml:AttributeValue>
         </saml:Attribute>
      </saml:AttributeStatement>
```

Sure I have put some * in the username string.

**IMPORTANT : Refer to step 10 c)** 
* Check the option* 
**Create user if not exists: **

**ATTRIBUTE MAPPING**
type the followin in the appropriate textbox :

```
Username : saml_username
Email Address : saml_username
First Name: saml_username
Surname: saml_username
```

Everything should be working after theses extra steps.

Cheers,

DaRockWildCoder
